[project]
        name = "famcore"
	obj = {
		name = "types.c",
		public = "types.H",
		headers = { "types.H", "syscall.H", "misc.H" }
	}
	obj = {
		name = "errno.c",
		public = "errno.H",
		headers = { "types.H", "errno.H", "misc.H", "syscall.H" }
	}
	obj = {
		name = "signal.c",
		headers = {
			"types.H",
			"errno.H",
			"syscall.H",
			"misc.H",
			"syscall_const.H",
			"limits.H"
			"sys.H"
		}
	}
	obj = {
		name = "format.c",
		public = "format.H",
		headers = {
			"types.H",
			"alloc.H",
			"misc.H",
			"format.H"
		}
	}
	obj = {
		name = "atomic.c",
		public = "atomic.H",
		headers = {
			"types.H",
			"atomic.H"
		}
	}
	obj = {
		name = "alloc.c",
		public = "alloc.H",
		headers = {
			"types.H",
			"errno.H",
			"env.H",
			"limits.H",
			"misc.H",
			"atomic.H",
			"syscall.H",
			"format.H",
			"sys.H",
			"alloc.H"
		}
	}
	obj = {
		name = "sysext.c",
		headers = {
			"types.H",
			"syscall.H",
			"syscall_const.H"
		}
	}
	obj = {
		name = "colors.c"
		public = "colors.H"
		headers = {
			"colors.H"
		}
	}
	obj = {
		name = "misc.c",
		public = "misc.H",
		headers = { "types.H", "misc.H", "limits.H", "errno.H" }
	}
	obj = {
		name = "env.c",
		public = "env.H",
		headers = { "types.H", "env.H" }
	}
	obj = {
		name = "init.c",
		public = "init.H",
		headers = {
			"types.H",
			"errno.H",
			"misc.H",
			"init.H",
			"syscall.H"
		}
	}
	obj = {
		name = "syscall.c",
		public = "syscall.H",
		headers = {
			"types.H",
			"errno.H",
			"misc.H",
			"init.H",
			"syscall.H"
		}
	}
[deps]

